### ISSUE TITLE
SPI not closed

### ISSUE THREAD

**Issue by KHome** [GregDMeyer/IT8951#12]
Hi, thank you very much for supporting with this nice python-lib.
In my setup I use https://www.smarthomeng.de/ to call a logic, which includes an update of the epaper.

I've missing a "close()" function for the display, which results in several opened SPIDEV ports. After a while my python instance can not open any file anymore. OS ERR24
I've helped myself by calling: "display.epd.spi.__del__()"

Could you add this kind a destructor?

**Comment by GregDMeyer** [comment]
I see. Yes, there is a nice way to do it. Just use the `del` statement. For example:

``` python
my_spi = SPI()  # create SPI object
...             # do some stuff with it
del my_spi      # object is deleted and file handle is closed
```

I think this is a better solution than adding a `close()` method, since the object would be useless after calling `close()` anyway. Let me know if you have any further question!
