### ISSUE TITLE
Missing from time import sleep in interface.py

### ISSUE THREAD

**Issue by Jacob-Bishop** [GregDMeyer/IT8951#13]
In `interface.py`, `wait_display_ready` includes a `sleep` command, but the imports for `interface.py` are missing a `from time import sleep`.

Thanks putting together this module!

**Comment by GregDMeyer** [comment]
thanks for this heads up, i'll fix it right now!

something I have never quite understood is that it seems that the chip has two ways to check for readiness: that method, which reads a register, and another method (which i have defined in spi.pyx) that checks the ready pin. it's never been clear to me what situation calls for which one of these. I guess I'll open an issue about it so I can figure it out for myself sometime.
