### ISSUE TITLE
SPI close, also closes all other GPIO configs

### ISSUE THREAD

**Issue by KHome** [GregDMeyer/IT8951#16]
Hi Greg,

by using the SPI.__del__ method I faced some weird side-effect. My GPIO Config got "lost". 

This is due to "spi.pyx" line "GPIO.cleanup(). 
It does exactly what it should do - it cleans up ALL gpio configs. 
`def __del__(self):
        GPIO.cleanup()
        if self.fd != -1:
            os.close(self.fd)`

Could you remove this line and directly close "self.fd" as done after checking. I see no other reason to use the cleanup here.
Best regards,
KHome

**Comment by GregDMeyer** [comment]
I think it's important to still clean up the GPIO pins, but I agree the fact that it cleared the config was bad. Now it will just clean up the ones that it uses, so the rest of your configuration should remain. Let me know if there is still any problem.
