### ISSUE TITLE
Separate requirements.txt for the tests and remove dependency on tkinter

### ISSUE THREAD

**Issue by FutureSharks** [GregDMeyer/IT8951#20]
Currently we need to install `tkinter` but this package is only required to run the tests I believe. This package is also not in requirements.txt.

Would it be possible to move the dependency on `tkinter` outside of the display driver? Then we could use this package without having to install `tkinter` and its X11 dependencies. It would be leaner 🙂

**Comment by GregDMeyer** [comment]
Thanks for opening the issue! This is discussed in #11 --- it is a super quick fix, I will just move the tkinter import to become conditional if it's needed. I just haven't gotten around to doing it yet. But with this reminder I will try to do it this afternoon :)
