### ISSUE TITLE
Partial refresh images

### ISSUE THREAD

**Issue by jokober** [GregDMeyer/IT8951#28]
Since waveshares IT8951 driver doesn't support partial refresh I was hoping this implementation might be able to do partial refreshes of images. Unfortunately I couldn't find any example code in the tests though. 

Is it possible to partially refresh images?

**Comment by GregDMeyer** [comment]
Yeah you can, for sure! the partial refresh doesn't care what it is displaying, I just used text as an example. If you display an image using the AutoEPDDisplay class (like in the example), then modify the image in `display.frame_buf` and then call `partial_update`, it should update only the parts that have changed.

**Comment by jokober** [comment]
It worked like a charm. Thanks for your great work!

**Comment by GregDMeyer** [comment]
awesome, glad to hear it! :)

**Comment by GregDMeyer** [comment]
btw the partial update usually updates a rectangle around the area that was changed, but if you use the "DU" update waveform it will only update the exact pixels that were changed!
