### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by SirDagen** [GregDMeyer/IT8951#3]
I am trying for an hour now. How can I use the display vertically. I can flip it, but how to use it vertically? 

I use PIL to draw an vertical image (1404x1872 instead of 1872x1404) and would like to push it to the display...

**Comment by GregDMeyer** [comment]
I think the best way to do it is just to rotate your image using `img.rotate(90, expand=True)` (or similar) before adding it to the frame buffer. (If you come up with a better way, would love to hear it!)

**Comment by SirDagen** [comment]
Oh my, you really know your trade. That's a nice solution. Thank you
