### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by sperez91** [GregDMeyer/IT8951#41]
I've been getting the following error when executing **pip install ./**:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-WsATgY/
See screenshot.

I've been googling fixes for this but nothing works. Anybody can help?

![2021-10-01 12_51_02-pi@raspberrypi_ ~_IT8951](https://user-images.githubusercontent.com/5923672/135678725-95d4f617-cb99-4534-915f-32aa28bef516.png)

**Comment by GregDMeyer** [comment]
Hi there! There is an easy fix, try running with `pip3` instead of `pip`, this should target Python 3 instead of Python 2. Sorry about that, I will update the README to make this more clear.

**Comment by sperez91** [comment]
Thank you so much! It works (:
